travis:
  secure:
    BINSTAR_TOKEN: hIypfBh6lVxf6W614wF6etLPZeusGJsv0HwjZsta1ZSDt25+62Lmo7uudTSpvHrkIuzQwRQTPSzWIrEAt2RplTHGwCzGmb/R0+qqE3bpX64GnwcGd7Ydso280JnxLLAVJf8bepMCdmPql7J7kpCbqYB92qB8qqf0Im2nOJ+9HjrNm/Bd5ByxDb3kii11NgpFdfbqAbV7EjDQmUhYMmtkpvZPepV2Hk/FyFNyDSlxsi9wr9EP9DMzQSV3IiKwO+mkO6BQZzD8PJWRXjaJKHvu+wwu2zNCovzfGM06S/ZfZivhsKrchL3d9EgSJY0oTdgVR7FIcqjRx6F2CMRD99E00oXW/TFa1y3Bll/EkUUnfn/0SaJ6B5VNsf52xPmxW3wpT5UMUhKe51/Koi373HT90ugcUQ8ghHYisGzZ8UvaeTfhFaY11UFE/cI38Tm3aE5fRwZRPqgxMJWGbWCwZ9LVzyJ3riGud1Y9WBNUcTqyVJWo9+tBLy+tqUz1QMF2w7DOscQdqzZOGLOD+CqBB4ZCd8nMV0hUbm8P1657HWoqSMildDU5mNZwdIfJrfqtLLeIxTAFJyZw0dftWYXCsG2HkHp67+if+q5T2RyykWyRd5R3Taxwq5dRL3k51zPYNzJmjlm2Q+HXpFt8v3+RlRVDo4jpoiODhwpSdqg/fpvduMM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
